@startuml

title __SEGREGATION's Class Diagram__\n

  namespace com.atguigu.principle.segregation {
    class com.atguigu.principle.segregation.A {
        + depend1()
        + depend2()
        + depend3()
    }
  }
  

  namespace com.atguigu.principle.segregation {
    class com.atguigu.principle.segregation.B {
        + operation1()
        + operation2()
        + operation3()
        + operation4()
        + operation5()
    }
  }
  

  namespace com.atguigu.principle.segregation {
    class com.atguigu.principle.segregation.C {
        + depend1()
        + depend4()
        + depend5()
    }
  }
  

  namespace com.atguigu.principle.segregation {
    class com.atguigu.principle.segregation.D {
        + operation1()
        + operation2()
        + operation3()
        + operation4()
        + operation5()
    }
  }
  

  namespace com.atguigu.principle.segregation {
    interface com.atguigu.principle.segregation.Interface1 {
        {abstract} + operation1()
        {abstract} + operation2()
        {abstract} + operation3()
        {abstract} + operation4()
        {abstract} + operation5()
    }
  }
  

  namespace com.atguigu.principle.segregation {
    class com.atguigu.principle.segregation.Segregation1 {
        {static} + main()
    }
  }
  

  com.atguigu.principle.segregation.B .up.|> com.atguigu.principle.segregation.Interface1
  com.atguigu.principle.segregation.D .up.|> com.atguigu.principle.segregation.Interface1


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
